version: "3"

networks:
  decimator_net:
    driver: bridge

services:
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: mongo
    networks:
      - decimator_net

  decimator_api:
    build: services/decimator_api
    image: decimator_api:${API_VERSION}
    container_name: decimator_api
    env_file:
      - ./services/decimator_api/.env.common
      - ./services/decimator_api/.env.docker
    networks:
      - decimator_net
    depends_on:
      - mongo
